name: Deploy to Render

on:
  push:
    branches: [main]  # Adaptez à votre branche principale (main ou master)
  workflow_dispatch:  # Permet de déclencher le workflow manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        # Si vous n'avez pas encore de tests, vous pouvez commenter cette étape
      
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}